import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { GetStaticProps } from "next";
import { getData } from "./api/hello";

export default function Home(props: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>The time is {props.time}</h1>
      </main>
    </>
  );
}

type Props = ReturnType<typeof getData>;
export const getStaticProps: GetStaticProps<Props> = async () => {
  const data = getData();
  return {
    props: {
      ...data,
    },
    revalidate: 10,
  };
};
